name: Test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, ruby-head, jruby ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y g++-4.8 pandoc
      - name: Test
        run: |
          gem install bundler -v '< 2.0'
          export CXX="g++-4.8"
          bundle install --jobs=3 --retry=3
          echo "Running sinatra tests..."
          bundle exec rake
